---
apiVersion: v1
kind: Pod
metadata:
  labels:
    job: build-service
spec:
  containers:
    - name: dind
      image: docker:18.05-dind
      imagePullPolicy: IfNotPresent
      env:
        - name: DOCKER_HOST
          value: tcp://localhost:2375
      securityContext:
        privileged: true
      tty: true
      volumeMounts:
        - name: docker-sock
          mountPath: /var/lib/docker
      resources:
        requests:
          cpu: 1
          memory: 1Gi
        limits:
          cpu: 1
          memory: 1Gi
  volumes:
    - name: docker-sock
      emptyDir: {}
